# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='社交')),
                ('link', models.URLField(max_length=512, verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=200, verbose_name='联系方式')),
                ('detail', models.CharField(max_length=512, verbose_name='详情')),
            ],
        ),
        migrations.CreateModel(
            name='ContributedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目')),
                ('link', models.URLField(max_length=512, verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='OpenSourceProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目')),
                ('link', models.URLField(max_length=512, verbose_name='链接')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='就职公司', max_length=200, verbose_name='公司')),
                ('position', models.CharField(max_length=200, verbose_name='职位')),
                ('entry_time', models.DateField(verbose_name='入职时间')),
                ('time_of_separation', models.DateField(blank=True, null=True, verbose_name='离职时间')),
                ('verbose_for_work', models.TextField(blank=True, null=True, verbose_name='工作描述')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
