# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-17 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text=b'\xe5\xb0\xb1\xe8\x81\x8c\xe5\x85\xac\xe5\x8f\xb8', max_length=200, verbose_name='\u516c\u53f8')),
                ('position', models.CharField(max_length=200, verbose_name='\u804c\u4f4d')),
                ('entry_time', models.DateField(verbose_name='\u5165\u804c\u65f6\u95f4')),
                ('time_of_separation', models.DateField(blank=True, null=True, verbose_name='\u79bb\u804c\u65f6\u95f4')),
                ('verbose_for_work', models.TextField(blank=True, null=True, verbose_name='\u5de5\u4f5c\u63cf\u8ff0')),
            ],
        ),
    ]
