# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0uuid'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(upload_to=b'upload', verbose_name='\u6587\u4ef6'),
        ),
    ]
