# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170403_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aboutme',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='ContributedProject',
        ),
        migrations.DeleteModel(
            name='OpenSourceProject',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(upload_to='upload', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
    ]
