# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161020_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u9605\u8bfb\u6570\u91cf'),
        ),
    ]
